server:
  port: ${SERVER_PORT:7801}
  ssl:
    enabled: false

spring:
  application:
    name: btc-server

  data:
    mongodb:
      host: 145.223.22.73
      port: 30001
      database: confeet
      username: adminuser
      password: password
      authentication-database: admin

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://145.223.22.73:32033/
    username: root
    password: live@Bottomhalf_001
    database: btc_meets


# LiveKit configuration
livekit:
  url: http://livekit-service.cf.svc.cluster.local:7880
  api-key: APIJByNUPVKqDS8
  api-secret: mcv0eMRL9uSw3fAna0jkDjxs4ZKBvpAM5WV9k3fOvk4B

#security:
#  jwt:
#    key: bottomhalfx12#@-emstum-api-servic-x#20$46@3211
#    issuer: bottomhalf-services
#    expiry-time-in-seconds: 3600
#    refresh-token-expiry-time-in-seconds: 72

#routes:
#  authorized:
#    - /api/auth/authenticateUser
#    - /api/auth
#    - /api/conference/token
#    - /api/meeting/validateMeeting